# Introduction to Numpy and Basic Linear Algebra Operations
---


[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/10hY5akl9UR5fRRAQKdvrZPnMwItqsyHI?usp=sharing)

## Array Creation

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2, 3.5, 5.1])

In [6]:
b.dtype

dtype('float64')

In [7]:
a = np.array(1,2,3,4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
a = np.array([1,2,3,4])  # RIGHT

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])

In [ ]:
b

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
np.empty( (2,3) )                                 # uninitialized

array([[1.4778531e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [11]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

## Printing Arrays

In [12]:
a = np.arange(6)                         # 1d array

In [13]:
print(a)

[0 1 2 3 4 5]


In [14]:
b = np.arange(12).reshape(4,3)           # 2d array

In [15]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
c = np.arange(24).reshape(2,3,4)         # 3d array

In [17]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [18]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [19]:
a = np.array( [20,30,40,50] )

In [20]:
b = np.arange( 4 )

In [21]:
b

array([0, 1, 2, 3])

In [22]:
c = a-b

In [23]:
c

array([20, 29, 38, 47])

In [24]:
b**2

array([0, 1, 4, 9])

In [25]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [26]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [27]:
A = np.array( [[1,1], [0,1]] )

In [28]:
B = np.array( [[2,0], [3,4]] )

In [29]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [30]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [31]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

## Frequently Used Operations in Neural Networks

Common operations in neural networks are [linear layers](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) and [non-linear activation functions](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html?highlight=relu#torch.nn.ReLU). We will replicate each of them using numpy.

The [linear layers](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) is described as:
$$y=xW^T + b$$
where:
* $y$; matrix of dependent variables size `number of examples` * `number of outputs`
* $x$; matrix of independent variables size `number of examples` * `number of features`
* $W$; matrix of weights size `number of outputs` * `number of features`
* $b$; matrix of biases size `number of examples` * `number of outputs`

In [64]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
W = np.array([[-1,-0.5,1]])
b = np.array([[1],[1],[1],[1]])
x.shape, W.shape, b.shape

((4, 3), (1, 3), (4, 1))

In [65]:
W.shape, W

((1, 3), array([[-1. , -0.5,  1. ]]))

In [66]:
W.T.shape, W.T #transpose

((3, 1), array([[-1. ],
        [-0.5],
        [ 1. ]]))

In [67]:
y = x@W.T + b
y

array([[ 2. ],
       [ 0.5],
       [-1. ],
       [-2.5]])

In [68]:
y.shape

(4, 1)

[Non-linear activation functions](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html?highlight=relu#torch.nn.ReLU) is simply applying some function to the results of linear layer; for example, applying ReLU function

$$ReLU(x) = x \text{ if } x>0 \text{ else } 0 $$

$$y = ReLU(xW^T + b)$$

In [74]:
def relu(x): return np.maximum(x,0)

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
W = np.array([[-1,-0.5,1]])
b = np.array([[1],[1],[1],[1]])
x.shape, W.shape, b.shape

((4, 3), (1, 3), (4, 1))

In [75]:
relu(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 0, 1, 2, 3])

In [76]:
y = relu(x@W.T + b)
y

array([[2. ],
       [0.5],
       [0. ],
       [0. ]])

During the course, we will redo these operations in a very similar manner using [Pytorch](https://pytorch.org/).