# Introduction to Numpy
---


## Array Creation

In [ ]:
import numpy as np

In [ ]:
a = np.array([2,3,4])

In [ ]:
a

array([2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b = np.array([1.2, 3.5, 5.1])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
a = np.array(1,2,3,4)    # WRONG

TypeError: ignored

In [ ]:
a = np.array([1,2,3,4])  # RIGHT

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.empty( (2,3) )                                 # uninitialized

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [ ]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

## Printing Arrays

In [ ]:
a = np.arange(6)                         # 1d array

In [ ]:
print(a)

[0 1 2 3 4 5]


In [ ]:
b = np.arange(12).reshape(4,3)           # 2d array

In [ ]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
c = np.arange(24).reshape(2,3,4)         # 3d array

In [ ]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [ ]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
a = np.array( [20,30,40,50] )

In [ ]:
b = np.arange( 4 )

In [ ]:
b

array([0, 1, 2, 3])

In [ ]:
c = a-b

In [ ]:
c

array([20, 29, 38, 47])

In [ ]:
b**2

array([0, 1, 4, 9])

In [ ]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [ ]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [ ]:
A = np.array( [[1,1], [0,1]] )

In [ ]:
B = np.array( [[2,0], [3,4]] )

In [ ]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [ ]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [ ]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])