# Entrace Example for AI Builders

จุดมุ่งหมายคือการทดสอบความรู้ปรับพื้นฐานสำหรับ AI Builders ทุกคำตอบสามารถหาได้จาก notebook ปรับพื้นฐาน `ai_builder_intro_python.ipynb`, `ai_builder_numpy.ipynb` และ `ai_builder_pandas.ipynb` 

เราหวังให้คุณพยามสุดความสามารถที่จะตอบ แต่ไม่จำเป็นต้องตอบได้ครบทุกข้อเพื่อที่จะได้รับการคัดเลือกเข้าโครงการ

## Python

1. หาก `a=1` และ `b=2.5` แล้ว, `c` = $0.5(a+2b^5)$, `c` มีค่าเท่าไหร่? $b^x$ เขียนใน Python ได้แบบนี้ `b**x`

In [4]:
a=1
b=2.5
c = #ใส่คำตอบตรงนี้
c

2. `a`, `b`, และ `c` เป็นตัวแปรชนิดอะไรบ้าง? (ลองใช้ `type(a)`)

3. จากตัวแปร `s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'`, เราจะดึงคำว่า `AI Good` ออกมาได้อย่างไร?

In [15]:
s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'

#ใส่คำตอบตรงนี้


'AI Good'

4. ใช้ loop `print` ทุก element ใน `l` ยกเว้น element ที่เขียนว่า `AI`

`l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']`

ลองใช้ `for` และ `if` เพื่อกรอง element ที่มีค่าเป็น `AI` ออก

In [17]:
l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']

#เขียน loop ตรงนี้


Builders
-
A
Program
For
Kids
Who
Wants
to
Good
Good


5. เขียนฟังชั่น `midpoint` ที่หาจุดกึ่งกลางระหว่างตัวเลข `a` และ `b` 

In [18]:
def midpoint(a, b):
    """
    Computes a midpoint between a and b.
    Hint: midpoint of a and b is (a+b)/2
    """
    ... #ใส่คำตอบตรงนี้

print(midpoint(1, 4))  # expected 2.5
print(midpoint(3, 3))  # expected 3
print(midpoint(-2, 2))  # expected 0

2.5
3.0
0.0


6. เขียนฟังชั่น `fizzbuzz` ที่รับตัวเลข `x`


- ถ้า `x` หารด้วย 2 ลงให้คืน string ว่า `fizz`
- ถ้า `x` หารด้วย 3 ลงให้คืน string ว่า `buzz`
- ถ้า `x` หารด้วยทั้ง 2 และ 3 ลงให้คืน string ว่า `fizzbuzz`
- นอกนั้นให้คืน `None`

ลองใช้ `if`, `elif` และ `else` ในฟังชั่น `fizzbuzz`

In [19]:
def fizzbuzz(x):
    ... #ใส่คำตอบตรงนี้

for i in range(20):
    print(i,fizzbuzz(i))

0 fizzbuzz
1 None
2 fizz
3 buzz
4 fizz
5 None
6 fizzbuzz
7 None
8 fizz
9 buzz
10 fizz
11 None
12 fizzbuzz
13 None
14 fizz
15 buzz
16 fizz
17 None
18 fizzbuzz
19 None


## Numpy and Linear Algebra

In [20]:
import numpy as np

1. สร้าง numpy array `a` ที่มีมิติ `3*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 9 (ลองใช้ `np.arange` และ `np.reshape`)

In [21]:
a = #ใส่คำตอบตรงนี้
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. สร้าง numpy array `b` ที่มีมิติ `4*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 12 (ลองใช้ `np.arange` และ `np.reshape`)

In [22]:
b = #ใส่คำตอบตรงนี้
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. เราสามารถหาค่า `a` dot product `b` ได้หรือไม่-เพราะอะไร (ลองใช้ `a.dot(b)` หรือ `a@b`)

In [23]:
#ใส่คำตอบตรงนี้


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

4. หาค่า `a` dot product (`b` transposed) (tranpose `b` ได้ด้วยคำสั่ง `b.T`)

In [24]:
#ใส่คำตอบตรงนี้


array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266]])

5. มิติ (แถวและคอลัมน์) ของ `a` และ `b` คืออะไร (ลองใช้ `a.shape`)

In [110]:
#ใส่คำตอบตรงนี้


((3, 3), (4, 3))

6. คูณทุก element ของ `a` ด้วย -1

In [111]:
#ใส่คำตอบตรงนี้


array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

7. เปลี่ยนมิติของ `b` ให้เป็น `2*2*3` (ลองใช้ `np.reshape`)

In [113]:
#ใส่คำตอบตรงนี้


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

8. ค่าเฉลี่ยของแต่ละแถวของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [115]:
#ใส่คำตอบตรงนี้


array([2., 5., 8.])

9. ค่าเฉลี่ยของแต่ละคอลัมน์ของ `a` (`3*3`) คืออะไร (ลองใช้ `np.mean` สังเกตว่าควรใช้ `axis=1` หรือ `axis=0`)

In [116]:
#ใส่คำตอบตรงนี้


array([4., 5., 6.])

10. ถ้าเราต้องการหา `[[1,2],[4,5]]` จาก `a` เราต้องเลือกอย่างไร

In [26]:
#เราสามารถ slice แต่ละส่วนของ `np.array` ได้เหมือนกับ list เช่น 
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [117]:
#ใส่คำตอบตรงนี้


array([[1, 2],
       [4, 5]])

## Pandas and Data Exploration

ดาวน์โหลดชุดข้อมูล [อุบัติเหตุบนโครงข่ายถนนของกระทรวงคมนาคม 2562](https://data.go.th/dataset/roadaccident) (ไฟล์ชื่อ `ubatiehtuthaangthnn.xlsx`) จาก [data.go.th](https://data.go.th/). ตอบคำถามต่อไปนี้

In [28]:
import pandas as pd

1. อ่านไฟล์ `ubatiehtuthaangthnn.xlsx` เข้ามาเป็น `pandas.DataFrame`; `df` มีกี่แถว-คอลัมน์? (ลองใช้ `df.shape`)

In [29]:
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)

#ใส่คำตอบตรงนี้


(19965, 20)

2. เรียกดู 20 แถวแรกและ 20 แถวสุดท้ายของ `df` (ลองใช้ `df.head(20)` และ `df.tail(20)`)

In [ ]:
#ใส่คำตอบตรงนี้


3. จังหวัดใดมีอุบัติเหตุเยอะที่สุดถ้าอ้างอิงจาก `df`? (ลองใช้ `df['จังหวัด'].value_counts()`)

In [32]:
#ใส่คำตอบตรงนี้


กรุงเทพมหานคร    1844
ชลบุรี            938
นครราชสีมา        877
สุพรรณบุรี        727
สมุทรปราการ       649
                 ... 
พังงา              72
ยะลา               72
ชัยภูมิ            70
อำนาจเจริญ         51
ระนอง              35
Name: จังหวัด, Length: 77, dtype: int64

4. เลือกเฉพาะแถวที่เป็นอุบัติเหตุที่มีผู้เสียชีวิต 0 ราย / มีอุบัติเหตุที่ไม่มีผู้เสียชีวิตกี่ครั้ง? (เราสามารถกรอง dataframe ได้ด้วยคำสั่ง `df[df['จำนวนผู้เสียชีวิต']==0]`)

In [33]:
#ใส่คำตอบตรงนี้


ปีที่เกิดเหตุ วันที่เกิดเหตุ   เวลา วันที่รายงาน เวลาที่รายงาน  \
0               2019     01/01/2019  00:00   02/01/2019         06:11   
1               2019     01/01/2019  00:03   13/02/2019         12:06   
3               2019     01/01/2019  00:20   02/01/2019         05:12   
4               2019     01/01/2019  00:25   01/01/2019         09:54   
5               2019     01/01/2019  00:30   01/01/2019         11:22   
...              ...            ...    ...          ...           ...   
19955           2019     31/12/2019  23:00   31/12/2019         23:37   
19956           2019     31/12/2019  23:10   01/01/2020         00:14   
19957           2019     31/12/2019  23:20   31/12/2019         23:53   
19958           2019     31/12/2019  23:20   01/01/2020         00:38   
19961           2019     31/12/2019  23:35   01/01/2020         00:14   

           ACC_CODE        หน่วยงาน  \
0      201901023254  กรมทางหลวงชนบท   
1      201902135341      กรมทางหลวง   
3      201901023234  กรมทางหลวงชนบท   
4      201901012972      กรมทางหลวง   
5      201901013012      กรมทางหลวง   
...             ...             ...   
19955  201912313628      กรมทางหลวง   
19956  202001013638      กรมทางหลวง   
19957  202001013632      กรมทางหลวง   
19958  202001013646      กรมทางหลวง   
19961  202001013642      กรมทางหลวง   

                                          สายทาง     ก.ม.       จังหวัด  \
0                            ทางหลวงชนบท ลบ.2029    4.000        ลพบุรี   
1        ทางหลวงแผ่นดินหมายเลข 24 ตอนควบคุม 0702  419.770   อุบลราชธานี   
3                            ทางหลวงชนบท ชม.4016    1.880     เชียงใหม่   
4       ทางหลวงแผ่นดินหมายเลข 225 ตอนควบคุม 0202   68.800     นครสวรรค์   
5        ทางหลวงแผ่นดินหมายเลข 41 ตอนควบคุม 0103   65.850         ชุมพร   
...                                          ...      ...           ...   
19955     ทางหลวงแผ่นดินหมายเลข 4 ตอนควบคุม 0501  145.400      เพชรบุรี   
19956    ทางหลวงแผ่นดินหมายเลข 44 ตอนควบคุม 0200   78.300  สุราษฎร์ธานี   
19957     ทางหลวงแผ่นดินหมายเลข 7 ตอนควบคุม 0109    5.900        ชลบุรี   
19958  ทางหลวงแผ่นดินหมายเลข 1147 ตอนควบคุม 0100    0.005         ลำพูน   
19961  ทางหลวงแผ่นดินหมายเลข 4034 ตอนควบคุม 0100   14.660        กระบี่   

                                  รถคันที่ 1    บริเวณที่เกิดเหตุ/ลักษณะทาง  \
0                              รถจักรยานยนต์  ทางตรง+ไม่มีความลาดชัน/ที่ราบ   
1      รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
3                              รถจักรยานยนต์  ทางตรง+ไม่มีความลาดชัน/ที่ราบ   
4      รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
5                       รถปิคอัพบรรทุก 4 ล้อ                 ทางแยกรูปตัว +   
...                                      ...                            ...   
19955  รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
19956                   รถปิคอัพบรรทุก 4 ล้อ                         ทางตรง   
19957  รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
19958                          รถจักรยานยนต์                    ทางโค้งปกติ   
19961                          รถจักรยานยนต์                 ทางแยกรูปตัว T   

                                มูลเหตุสันนิษฐาน ลักษณะการเกิดอุบัติเหตุ   \
0                                        เมาสุรา                   อื่น ๆ   
1                             ขับรถเร็วเกินกำหนด          ชนอุปกรณ์งานทาง   
3                                        เมาสุรา             รถยนต์ชนรถไฟ   
4                      คนหรือรถตัดหน้ากระชั้นชิด            พลิกคว่ำตกถนน   
5      ไม่ให้สิทธิรถที่มาก่อนผ่านทาง เช่น ทางแยก    ชนกัน/ชนยานพาหนะอื่นๆ   
...                                          ...                      ...   
19955                         ขับรถเร็วเกินกำหนด            พลิกคว่ำตกถนน   
19956                         ขับรถเร็วเกินกำหนด            พลิกคว่ำตกถนน   
19957                         ขับรถเร็วเกินกำหนด                   ชนท้าย   
19958                         ขับรถเร็วเก

5. ค่าเฉลี่ยของ latitude, logitude ของอุบัติเหตุที่เกิดขึ้นในจังหวัดเชียงใหม่อยู่ที่เท่าใด? (กรองให้เหลือแค่จังหวัดเชียงใหม่แล้วหาค่าเฉลี่ยด้วยคำสั่ง `df.LATITUDE.mean()` และ `df.LONGITUDE.mean()`)

In [34]:
#ใส่คำตอบตรงนี้


(18.91090138416936, 98.91462670826341)

6. `ลักษณะการเกิดอุบัติเหตุ ` แบบใดมี `จำนวนผู้เสียชวิต` โดยเฉลี่ยสูงที่สุด?

In [35]:
#Hint 1: df[COLUMN_NAME].value_counts().reset_index() will give you dataframe version of value counts
#Hint 2: See what sort_values() does

#ใส่คำตอบตรงนี้

ลักษณะการเกิดอุบัติเหตุ   จำนวนผู้เสียชวิต
8                                     ชนรถไฟ          6.000000
2                                   ชนขณะแซง          0.794118
25                      รถยนต์พลิกคว่ำ ตกถนน          0.750000
18    รถจักรยานยนต์ชนรถจักรยานพลิกคว่ำ ตกถนน          0.750000
12       ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง)          0.615385
4                               ชนคนเดินเท้า          0.610714
0                      ชนกัน/ชนยานพาหนะอื่นๆ          0.437209
7                                    ชนรถจอด          0.436548
13                                   ตกจากรถ          0.428571
17                         รถจักรยานยนต์ชนคน          0.400000
11                     ชนเป็นมุมบริเวณทางแยก          0.385135
21            รถยนต์ชนรถจักรยานยนต์/รถสามล้อ          0.250000
1                          ชนกันหรือเฉี่ยวชน          0.232843
23                     รถยนต์ชนวัตถุ สิ่งของ          0.172414
9                              ชนสิ่งกีดขวาง          0.161616
28                              เลี้ยว/ถอยชน          0.157895
6                                     ชนท้าย          0.154588
27                                  เฉี่ยวชน          0.152490
22                              รถยนต์ชนรถไฟ          0.148148
16      รถจักรยานยนต์ชนกับรถจักรยาน รถสามล้อ          0.142857
3                                   ชนขอบทาง          0.128889
26                                    อื่น ๆ          0.128205
15                             พลิกคว่ำตกถนน          0.106300
29           เสียหลัก ไปอยู่ในช่องจราจรอื่นๆ          0.080128
5   ชนตู้เก็บเงิน ไม้กั้นเลน อุปกรณ์เก็บเงิน          0.052632
10                           ชนอุปกรณ์งานทาง          0.047334
24           รถยนต์ชนสัตว์ รถลากจูงด้วยสัตว์          0.035714
20                               รถยนต์ชนกัน          0.000000
19                     รถจักรยานยนต์ชนรถยนต์          0.000000
14                                  พลิกคว่ำ          0.000000

7. อุบัติเหตุที่เกิดจาก `มูลเหตุสันนิษฐาน` เป็น `ขับรถเร็วเกินกำหนด` มีโอกาสทำให้มีผู้เสียชีวิตมากกว่า `มูลเหตุสันนิษฐาน` อื่นหรือไม่?

In [34]:
#สร้าง column `drive_fast_flag` ที่จะเป็น 1 เมื่อ 'มูลเหตุสันนิษฐาน' เป็น 'ขับรถเร็วเกินกำหนด' (นอกนั้นเป็น 0) โดยใช้ map และ lambda
df['drive_fast_flag'] = df['มูลเหตุสันนิษฐาน'].map(lambda x: 1 if x=='ขับรถเร็วเกินกำหนด' else 0)

#สร้าง column `has_death` ที่จะเป็น 1 เมื่อ 'จำนวนผู้เสียชีวิต' มากกว่า 1 คน (นอกนั้นเป็น 0) โดยใช้ map และ lambda
df['has_death'] = #ใส่คำตอบตรงนี้

#ใช้ groupby('drive_fast_flag').has_death.mean() เพื่อหาค่าเฉลี่ยของอุบัติเหตุที่มีผู้เสียชีวิต แบ่งด้วย drive_fast_flag


drive_fast_flag
0    0.157192
1    0.124128
Name: has_death, dtype: float64