# Entrace Example for AI Builders

จุดมุ่งหมายคือการทดสอบความรู้ปรับพื้นฐานสำหรับ AI Builders ทุกคำตอบสามารถหาได้จาก notebook ปรับพื้นฐาน `ai_builder_intro_python.ipynb`, `ai_builder_numpy.ipynb` และ `ai_builder_pandas.ipynb` 

เราหวังให้คุณพยามสุดความสามารถที่จะตอบ แต่ไม่จำเป็นต้องตอบได้ครบทุกข้อเพื่อที่จะได้รับการคัดเลือกเข้าโครงการ

## Python

1. สร้างตัวแปร `a=1` และ `b=2.5`

In [4]:
a= #write your answer here
b= #write your answer here
a,b

(1, 2.5)

2. จากตัวแปร `a` และ `b` ในข้อที่แล้ว, `c` = $0.5(a+2b^5)$, `c` มีค่าเท่าไหร่?

In [ ]:
#Hint: b to the power of 5 is written as b**5

3. `a`, `b`, และ `c` เป็นตัวแปรชนิดอะไรบ้าง?

4. สร้าง `d`, `e`, `f` โดยให้แต่ละอันเป็นตัวแปรแบบ string ของ `a`, `b`, `c`

5. `a`+`b`+`c` ต่างจาก `d`+`e`+`f` อย่างไร? ทำไมถึงรัน `a`+`d` ไม่ผ่าน?

In [ ]:
#Hint: what types of variables are these?

6. จากตัวแปร `s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'`, เราจะดึงคำว่า `Program` ออกมาได้อย่างไร?

In [1]:
s = 'AI Builders - A Program For Kids Who Wants to AI Good Good'

7. ใช้ loop `print` ทุก element ใน `l` ยกเว้น element ที่เขียนว่า `AI`

`l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']`

In [2]:
l = ['AI','Builders','-','A','Program','For','Kids','Who','Wants','to','AI','Good','Good']

#write your for-loop here
#Hint: you need if-else to filter out 'AI'

8. เลือก element ที่ 3 **จากท้าย**ถึง element สุดท้ายของ `l`

9. เขียนฟังชั่น `circle_area` ที่จะหาพื้นที่ของวงกลมจากรัศมี `r`

In [3]:
import math
pi = math.pi

def circle_area(r):
    #replace pass with you code
    pass

#running this should return area
circle_area(1)

10. เขียนฟังชั่น `fizzbuzz` ที่รับตัวเลข `x`


- ถ้า `x` หารด้วย 2 ลงให้คืน string ว่า `fizz`
- ถ้า `x` หารด้วย 3 ลงให้คืน string ว่า `buzz`
- ถ้า `x` หารด้วยทั้ง 2 และ 3 ลงให้คืน string ว่า `fizzbuzz`
- นอกนั้นให้คืน `None`

In [102]:
def fizzbuzz(x):
    #replace pass with you code
    #Hint: you need to use if, elif and else
    pass

for i in range(20):
    print(i,fizzbuzz(i))

0 fizzbuzz
1 None
2 fizz
3 buzz
4 fizz
5 None
6 fizzbuzz
7 None
8 fizz
9 buzz
10 fizz
11 None
12 fizzbuzz
13 None
14 fizz
15 buzz
16 fizz
17 None
18 fizzbuzz
19 None


## Numpy and Linear Algebra

In [103]:
import numpy as np

1. สร้าง numpy array `a` ที่มีมิติ `3*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 9

In [105]:
a = #write your answer here
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. สร้าง numpy array `b` ที่มีมิติ `4*3` โดยมีค่าเป็นตัวเลขจาก 1 ถึง 12

In [107]:
b = #write your answer here
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

3. เราสามารถหาค่า `a` dot product `b` ได้หรือไม่-เพราะอะไร

In [108]:
#Hint: Look at dimensions of a and b
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

4. หาค่า `a` dot product (`b` transposed)

In [109]:
#Hint: b transposed is b.T

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266]])

5. มิติ (แถวและคอลัมน์) ของ `a` และ `b` คืออะไร

((3, 3), (4, 3))

6. คูณทุก element ของ `a` ด้วย -1

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

7. เปลี่ยนมิติของ `b` ให้เป็น `2*2*3`

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

8. ค่าเฉลี่ยของแต่ละแถวของ `a` (`3*3`) คืออะไร

In [115]:
#Hint: find row mean using a.mean(1)

array([2., 5., 8.])

9. ค่าเฉลี่ยของแต่ละคอลัมน์ของ `a` (`3*3`) คืออะไร

In [116]:
#Hint: find column mean using a.mean(0)

array([4., 5., 6.])

10. ถ้าเราต้องการหา `[[1,2],[4,5]]` จาก `a` เราต้องเลือกอย่างไร

array([[1, 2],
       [4, 5]])

## Pandas and Data Exploration

ดาวน์โหลดชุดข้อมูล [อุบัติเหตุบนโครงข่ายถนนของกระทรวงคมนาคม 2562](https://data.go.th/dataset/roadaccident) (ไฟล์ชื่อ `ubatiehtuthaangthnn.xlsx`) จาก [data.go.th](https://data.go.th/). ตอบคำถามต่อไปนี้

In [9]:
import pandas as pd

1. อ่านไฟล์ `ubatiehtuthaangthnn.xlsx` เข้ามาเป็น `pandas.DataFrame`; `df` มีกี่แถว-คอลัมน์?

In [13]:
url = 'https://archive.org/download/ubatiehtuthaangthnn/ubatiehtuthaangthnn.xlsx'
df = pd.read_excel(url)
#Hint: find dimension of df using df.shape

(19965, 20)

2. เรียกดู 20 แถวแรกและ 20 แถวสุดท้ายของ `df`

In [14]:
#Hint: find head

ปีที่เกิดเหตุ วันที่เกิดเหตุ   เวลา วันที่รายงาน เวลาที่รายงาน  \
0            2019     01/01/2019  00:00   02/01/2019         06:11   
1            2019     01/01/2019  00:03   13/02/2019         12:06   
2            2019     01/01/2019  00:05   01/01/2019         09:52   
3            2019     01/01/2019  00:20   02/01/2019         05:12   
4            2019     01/01/2019  00:25   01/01/2019         09:54   
5            2019     01/01/2019  00:30   01/01/2019         11:22   
6            2019     01/01/2019  00:30   03/01/2019         11:16   
7            2019     01/01/2019  00:35   01/01/2019         09:04   
8            2019     01/01/2019  00:40   01/01/2019         03:59   
9            2019     01/01/2019  00:45   01/01/2019         09:57   
10           2019     01/01/2019  00:45   01/01/2019         12:16   
11           2019     01/01/2019  00:45   02/01/2019         02:51   
12           2019     01/01/2019  01:00   01/01/2019         23:25   
13           2019     01/01/2019  01:00   02/01/2019         03:42   
14           2019     01/01/2019  01:00   02/01/2019         14:00   
15           2019     01/01/2019  01:04   01/01/2019         09:51   
16           2019     01/01/2019  01:15   02/01/2019         05:52   
17           2019     01/01/2019  01:20   01/01/2019         11:02   
18           2019     01/01/2019  01:20   01/01/2019         10:26   
19           2019     01/01/2019  01:30   01/01/2019         09:17   

        ACC_CODE        หน่วยงาน                                     สายทาง  \
0   201901023254  กรมทางหลวงชนบท                        ทางหลวงชนบท ลบ.2029   
1   201902135341      กรมทางหลวง    ทางหลวงแผ่นดินหมายเลข 24 ตอนควบคุม 0702   
2   201901012979      กรมทางหลวง  ทางหลวงแผ่นดินหมายเลข 3168 ตอนควบคุม 0100   
3   201901023234  กรมทางหลวงชนบท                        ทางหลวงชนบท ชม.4016   
4   201901012972      กรมทางหลวง   ทางหลวงแผ่นดินหมายเลข 225 ตอนควบคุม 0202   
5   201901013012      กรมทางหลวง    ทางหลวงแผ่นดินหมายเลข 41 ตอนควบคุม 0103   
6   201901073685  กรมทางหลวงชนบท                        ทางหลวงชนบท มส.3007   
7   201901012973      กรมทางหลวง   ทางหลวงแผ่นดินหมายเลข 309 ตอนควบคุม 0302   
8   201901012934      กรมทางหลวง   ทางหลวงแผ่นดินหมายเลข 406 ตอนควบคุม 0101   
9   201901012969      กรมทางหลวง  ทางหลวงแผ่นดินหมายเลข 3157 ตอนควบคุม 0102   
10  201901013014      กรมทางหลวง    ทางหลวงแผ่นดินหมายเลข 41 ตอนควบคุม 0103   
11  201901023212      กรมทางหลวง    ทางหลวงแผ่นดินหมายเลข 11 ตอนควบคุม 0800   
12  201901013180      กรมทางหลวง     ทางหลวงแผ่นดินหมายเลข 1 ตอนควบคุม 0403   
13  201901023216      กรมทางหลวง  ทางหลวงแผ่นดินหมายเลข 4024 ตอนควบคุม 0102   
14  201901023338      กรมทางหลวง     ทางหลวงแผ่นดินหมายเลข 4 ตอนควบคุม 0302   
15  201901012967      กรมทางหลวง     ทางหลวงแผ่นดินหมายเลข 1 ตอนควบคุม 0300   
16  201901023249      กรมทางหลวง  ทางหลวงแผ่นดินหมายเลข 3188 ตอนควบคุม 0101   
17  201901012985      กรมทางหลวง  ทางหลวงแผ่นดินหมายเลข 2067 ตอนควบคุม 0101   
18  201901012986      กรมทางหลวง  ทางหลวงแผ่นดินหมายเลข 3168 ตอนควบคุม 0100   
19  201901012961      กรมทางหลวง   ทางหลวงแผ่นดินหมายเลข 403 ตอนควบคุม 0201   

       ก.ม.          จังหวัด                             รถคันที่ 1  \
0     4.000           ลพบุรี                          รถจักรยานยนต์   
1   419.770      อุบลราชธานี  รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ   
2     1.700  ประจวบคีรีขันธ์                          รถจักรยานยนต์   
3     1.880        เชียงใหม่                          รถจักรยานยนต์   
4    68.800        นครสวรรค์  รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ   
5    65.850            ชุมพร                   รถปิคอัพบรรทุก 4 ล้อ   
6     2.000       แม่ฮ่องสอน                          รถจักรยานยนต์   
7    96.586        สิงห์บุรี                          รถจักรยานยนต์   
8    38.150            สงขลา                          รถจักรยานยนต์   
9    73.800             ตราด                          รถจักรยานยนต์   
10   61.900            ชุมพร                          รถจักรยานยนต์   
11  533.400          

In [15]:
#Hint: find tail

ปีที่เกิดเหตุ วันที่เกิดเหตุ   เวลา วันที่รายงาน เวลาที่รายงาน  \
19945           2019     31/12/2019  22:20   01/01/2020         05:00   
19946           2019     31/12/2019  22:20   01/01/2020         10:02   
19947           2019     31/12/2019  22:26   01/01/2020         06:12   
19948           2019     31/12/2019  22:30   31/12/2019         23:35   
19949           2019     31/12/2019  22:30   01/01/2020         10:05   
19950           2019     31/12/2019  22:38   02/01/2020         12:21   
19951           2019     31/12/2019  22:40   31/12/2019         23:12   
19952           2019     31/12/2019  22:40   31/12/2019         23:21   
19953           2019     31/12/2019  22:40   01/01/2020         01:25   
19954           2019     31/12/2019  22:40   01/01/2020         01:46   
19955           2019     31/12/2019  23:00   31/12/2019         23:37   
19956           2019     31/12/2019  23:10   01/01/2020         00:14   
19957           2019     31/12/2019  23:20   31/12/2019         23:53   
19958           2019     31/12/2019  23:20   01/01/2020         00:38   
19959           2019     31/12/2019  23:30   01/01/2020         00:18   
19960           2019     31/12/2019  23:30   01/01/2020         09:38   
19961           2019     31/12/2019  23:35   01/01/2020         00:14   
19962           2019     31/12/2019  23:40   01/01/2020         00:58   
19963           2019     31/12/2019  23:40   01/01/2020         06:44   
19964           2019     31/12/2019  23:45   01/01/2020         20:42   

           ACC_CODE        หน่วยงาน  \
19945  202001013666      กรมทางหลวง   
19946  202001013734      กรมทางหลวง   
19947  202001013691      กรมทางหลวง   
19948  201912313629      กรมทางหลวง   
19949  202001013739      กรมทางหลวง   
19950  202001024037  กรมทางหลวงชนบท   
19951  201912313620      กรมทางหลวง   
19952  201912313624      กรมทางหลวง   
19953  202001013649      กรมทางหลวง   
19954  202001013652      กรมทางหลวง   
19955  201912313628      กรมทางหลวง   
19956  202001013638      กรมทางหลวง   
19957  202001013632      กรมทางหลวง   
19958  202001013646      กรมทางหลวง   
19959  202001013637      กรมทางหลวง   
19960  202001013732      กรมทางหลวง   
19961  202001013642      กรมทางหลวง   
19962  202001013647      กรมทางหลวง   
19963  202001013681  กรมทางหลวงชนบท   
19964  202001013882      กรมทางหลวง   

                                          สายทาง      ก.ม.       จังหวัด  \
19945  ทางหลวงแผ่นดินหมายเลข 2445 ตอนควบคุม 0101    20.200     บุรีรัมย์   
19946   ทางหลวงแผ่นดินหมายเลข 212 ตอนควบคุม 0304   382.000        นครพนม   
19947  ทางหลวงแผ่นดินหมายเลข 4021 ตอนควบคุม 0100     6.150        ภูเก็ต   
19948     ทางหลวงแผ่นดินหมายเลข 4 ตอนควบคุม 1103  1040.540          ตรัง   
19949  ทางหลวงแผ่นดินหมายเลข 3472 ตอนควบคุม 0100     7.300    สุพรรณบุรี   
19950                        ทางหลวงชนบท สร.4034     5.640      สุรินทร์   
19951  ทางหลวงแผ่นดินหมายเลข 3350 ตอนควบคุม 0100     2.350    สุพรรณบุรี   
19952   ทางหลวงแผ่นดินหมายเลข 321 ตอนควบคุม 0300   103.800    สุพรรณบุรี   
19953     ทางหลวงแผ่นดินหมายเลข 2 ตอนควบคุม 0601   440.864      อุดรธานี   
19954  ทางหลวงแผ่นดินหมายเลข 3195 ตอนควบคุม 0201    12.800       อ่างทอง   
19955     ทางหลวงแผ่นดินหมายเลข 4 ตอนควบคุม 0501   145.400      เพชรบุรี   
19956    ทางหลวงแผ่นดินหมายเลข 44 ตอนควบคุม 0200    78.300  สุราษฎร์ธานี   
19957     ทางหลวงแผ่นดินหมายเลข 7 ตอนควบคุม 0109     5.900        ชลบุรี   
19958  ทางหลวงแผ่นดินหมายเลข 1147 ตอนควบคุม 0100     0.005         ลำพูน   
19959   ทางหลวงแผ่นดินหมายเลข 118 ตอนควบคุม 0100    11.150     เชียงใหม่   
19960  ทางหลวงแผ่นดินหมายเลข 3549 ตอนควบคุม 0100     1.250     กาญจนบุรี   
19961  ทางหลวงแผ่นดินหมายเลข 4034 ตอนควบคุม 0100    14.660        กระบี่   
19962     ทางหลวงแผ่นดินหมายเลข 4 ตอนควบคุม 0802   601.120         ระนอง   
19963                        ทางหลวงชนบท ชม.3029     5.600     เชียงใหม่   
19964  ทางหลวงแผ่นดินหมายเลข 3268 ตอนควบคุม 0103    22.000   สมุทรปราการ   

                                  รถคันที่ 1  \
19945   

3. จังหวัดใดมีอุบัติเหตุเยอะที่สุดถ้าอ้างอิงจาก `df`?

In [9]:
#Hint: see what df.value_counts() does

กรุงเทพมหานคร    1844
ชลบุรี            938
นครราชสีมา        877
สุพรรณบุรี        727
สมุทรปราการ       649
                 ... 
พังงา              72
ยะลา               72
ชัยภูมิ            70
อำนาจเจริญ         51
ระนอง              35
Name: จังหวัด, Length: 77, dtype: int64

4. เลือกเฉพาะแถวที่เป็นอุบัติเหตุที่มีผู้เสียชีวิต 0 ราย / มีอุบัติเหตุที่ไม่มีผู้เสียชีวิตกี่ครั้ง?

In [10]:
#Hint: filter a dataframe using df[df['จำนวนผู้เสียชีวิต']==0]

ปีที่เกิดเหตุ วันที่เกิดเหตุ   เวลา วันที่รายงาน เวลาที่รายงาน  \
0               2019     01/01/2019  00:00   02/01/2019         06:11   
1               2019     01/01/2019  00:03   13/02/2019         12:06   
3               2019     01/01/2019  00:20   02/01/2019         05:12   
4               2019     01/01/2019  00:25   01/01/2019         09:54   
5               2019     01/01/2019  00:30   01/01/2019         11:22   
...              ...            ...    ...          ...           ...   
19955           2019     31/12/2019  23:00   31/12/2019         23:37   
19956           2019     31/12/2019  23:10   01/01/2020         00:14   
19957           2019     31/12/2019  23:20   31/12/2019         23:53   
19958           2019     31/12/2019  23:20   01/01/2020         00:38   
19961           2019     31/12/2019  23:35   01/01/2020         00:14   

           ACC_CODE        หน่วยงาน  \
0      201901023254  กรมทางหลวงชนบท   
1      201902135341      กรมทางหลวง   
3      201901023234  กรมทางหลวงชนบท   
4      201901012972      กรมทางหลวง   
5      201901013012      กรมทางหลวง   
...             ...             ...   
19955  201912313628      กรมทางหลวง   
19956  202001013638      กรมทางหลวง   
19957  202001013632      กรมทางหลวง   
19958  202001013646      กรมทางหลวง   
19961  202001013642      กรมทางหลวง   

                                          สายทาง     ก.ม.       จังหวัด  \
0                            ทางหลวงชนบท ลบ.2029    4.000        ลพบุรี   
1        ทางหลวงแผ่นดินหมายเลข 24 ตอนควบคุม 0702  419.770   อุบลราชธานี   
3                            ทางหลวงชนบท ชม.4016    1.880     เชียงใหม่   
4       ทางหลวงแผ่นดินหมายเลข 225 ตอนควบคุม 0202   68.800     นครสวรรค์   
5        ทางหลวงแผ่นดินหมายเลข 41 ตอนควบคุม 0103   65.850         ชุมพร   
...                                          ...      ...           ...   
19955     ทางหลวงแผ่นดินหมายเลข 4 ตอนควบคุม 0501  145.400      เพชรบุรี   
19956    ทางหลวงแผ่นดินหมายเลข 44 ตอนควบคุม 0200   78.300  สุราษฎร์ธานี   
19957     ทางหลวงแผ่นดินหมายเลข 7 ตอนควบคุม 0109    5.900        ชลบุรี   
19958  ทางหลวงแผ่นดินหมายเลข 1147 ตอนควบคุม 0100    0.005         ลำพูน   
19961  ทางหลวงแผ่นดินหมายเลข 4034 ตอนควบคุม 0100   14.660        กระบี่   

                                  รถคันที่ 1    บริเวณที่เกิดเหตุ/ลักษณะทาง  \
0                              รถจักรยานยนต์  ทางตรง+ไม่มีความลาดชัน/ที่ราบ   
1      รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
3                              รถจักรยานยนต์  ทางตรง+ไม่มีความลาดชัน/ที่ราบ   
4      รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
5                       รถปิคอัพบรรทุก 4 ล้อ                 ทางแยกรูปตัว +   
...                                      ...                            ...   
19955  รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
19956                   รถปิคอัพบรรทุก 4 ล้อ                         ทางตรง   
19957  รถยนต์นั่งส่วนบุคคล/รถยนต์นั่งสาธารณะ                         ทางตรง   
19958                          รถจักรยานยนต์                    ทางโค้งปกติ   
19961                          รถจักรยานยนต์                 ทางแยกรูปตัว T   

                                มูลเหตุสันนิษฐาน ลักษณะการเกิดอุบัติเหตุ   \
0                                        เมาสุรา                   อื่น ๆ   
1                             ขับรถเร็วเกินกำหนด          ชนอุปกรณ์งานทาง   
3                                        เมาสุรา             รถยนต์ชนรถไฟ   
4                      คนหรือรถตัดหน้ากระชั้นชิด            พลิกคว่ำตกถนน   
5      ไม่ให้สิทธิรถที่มาก่อนผ่านทาง เช่น ทางแยก    ชนกัน/ชนยานพาหนะอื่นๆ   
...                                          ...                      ...   
19955                         ขับรถเร็วเกินกำหนด            พลิกคว่ำตกถนน   
19956                         ขับรถเร็วเกินกำหนด            พลิกคว่ำตกถนน   
19957                         ขับรถเร็วเกินกำหนด                   ชนท้าย   
19958                         ขับรถเร็วเก

5. ค่าเฉลี่ยของ latitude, logitude ของอุบัติเหตุที่เกิดขึ้นในจังหวัดเชียงใหม่อยู่ที่เท่าใด?

In [12]:
#Hint: Filter by chiangmai first then find mean of each column df.LATITUDE.mean() and df.LONGITUDE.mean()

(18.91090138416936, 98.91462670826341)

6. `ลักษณะการเกิดอุบัติเหตุ ` แบบใดมี `จำนวนผู้เสียชวิต` โดยเฉลี่ยสูงที่สุด?

In [21]:
#Hint 1: df[COLUMN_NAME].value_counts().reset_index() will give you dataframe version of value counts
#Hint 2: See what sort_values() does

ลักษณะการเกิดอุบัติเหตุ   จำนวนผู้เสียชวิต
8                                     ชนรถไฟ          6.000000
2                                   ชนขณะแซง          0.794118
25                      รถยนต์พลิกคว่ำ ตกถนน          0.750000
18    รถจักรยานยนต์ชนรถจักรยานพลิกคว่ำ ตกถนน          0.750000
12       ชนในทิศทางตรงกันข้าม (ไม่ใช่การแซง)          0.615385
4                               ชนคนเดินเท้า          0.610714
0                      ชนกัน/ชนยานพาหนะอื่นๆ          0.437209
7                                    ชนรถจอด          0.436548
13                                   ตกจากรถ          0.428571
17                         รถจักรยานยนต์ชนคน          0.400000
11                     ชนเป็นมุมบริเวณทางแยก          0.385135
21            รถยนต์ชนรถจักรยานยนต์/รถสามล้อ          0.250000
1                          ชนกันหรือเฉี่ยวชน          0.232843
23                     รถยนต์ชนวัตถุ สิ่งของ          0.172414
9                              ชนสิ่งกีดขวาง          0.161616
28                              เลี้ยว/ถอยชน          0.157895
6                                     ชนท้าย          0.154588
27                                  เฉี่ยวชน          0.152490
22                              รถยนต์ชนรถไฟ          0.148148
16      รถจักรยานยนต์ชนกับรถจักรยาน รถสามล้อ          0.142857
3                                   ชนขอบทาง          0.128889
26                                    อื่น ๆ          0.128205
15                             พลิกคว่ำตกถนน          0.106300
29           เสียหลัก ไปอยู่ในช่องจราจรอื่นๆ          0.080128
5   ชนตู้เก็บเงิน ไม้กั้นเลน อุปกรณ์เก็บเงิน          0.052632
10                           ชนอุปกรณ์งานทาง          0.047334
24           รถยนต์ชนสัตว์ รถลากจูงด้วยสัตว์          0.035714
20                               รถยนต์ชนกัน          0.000000
19                     รถจักรยานยนต์ชนรถยนต์          0.000000
14                                  พลิกคว่ำ          0.000000

7. อุบัติเหตุที่เกิดจาก `มูลเหตุสันนิษฐาน` เป็น `ขับรถเร็วเกินกำหนด` มีโอกาสทำให้มีผู้เสียชีวิตมากกว่า `มูลเหตุสันนิษฐาน` อื่นหรือไม่?

In [34]:
#Hint: you might want to create flags for those accidents caused by drive fast and those that have deaths first, then do groupby
df['drive_fast_flag'] = #write your answer here
df['has_death'] = #write your answer here
df.groupby('drive_fast_flag').has_death.mean()

drive_fast_flag
0    0.157192
1    0.124128
Name: has_death, dtype: float64

8. บันทึก `df` เป็นไฟล์ `small_accident.csv` โดยเอาแค่คอลัมน์ `จังหวัด`, `มูลเหตุสันนิษฐาน`, `ลักษณะการเกิดอุบัติเหตุ`, `จำนวนผู้เสียชีวิต` และ `รวมจำนวนผู้บาดเจ็บ`

9. อุบัติเหตุเกิดขึ้น `เวลา` ใดบ่อยที่สุด? นับเฉพาะชั่วโมง

In [41]:
#Hint: you might want to get hours first, then groupby
df['hrs'] = #write your answer here
df.groupby('hrs').ACC_CODE.count()

hrs
0      652
1      695
2      633
3      612
4      614
5      613
6      695
7      869
8      868
9      879
10     958
11     953
12     852
13    1002
14    1064
15    1091
16    1127
17     957
18     897
19     994
20     865
21     703
22     649
23     723
Name: ACC_CODE, dtype: int64

10. `df` มีคอลัมน์อะไรบ้าง?

Index(['ปีที่เกิดเหตุ', 'วันที่เกิดเหตุ', 'เวลา', 'วันที่รายงาน',
       'เวลาที่รายงาน', 'ACC_CODE', 'หน่วยงาน', 'สายทาง', 'ก.ม.', 'จังหวัด',
       'รถคันที่ 1', 'บริเวณที่เกิดเหตุ/ลักษณะทาง', 'มูลเหตุสันนิษฐาน',
       'ลักษณะการเกิดอุบัติเหตุ ', 'จำนวนรถที่เกิดเหตุ\n(รวมคันที่ 1)',
       'จำนวนผู้เสียชวิต', 'รวมจำนวนผู้บาดเจ็บ', 'สภาพอากาศ', 'LATITUDE',
       'LONGITUDE', 'drive_fast_flag', 'has_death', 'hrs'],
      dtype='object')